# Site settings
title: "Sequences - A Dance Video"
description: Check out the cool things you can build using Scratch! Happy coding!
baseurl: "/handout" # local call: $ jekyll serve --baseurl ''
url: "http://goodcodexyz.github.io/handout"
# Build settings
repository: goodcodexyz/handout
markdown: kramdown
collections:
  tasks:
    output: true
