# Site settings
title: Super Animators
description: Checkout the cool things you can build using Scratch! Happy coding!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goodcodexyz.github.io/handout"
# Build settings
repository: goodcodexyz/handout
markdown: kramdown
collections:
  - tasks
