# Site settings
title: Super Animators
description: Checkout the cool things you can build using Scratch! Happy coding!
baseurl: "/" # local call: $ jekyll serve --baseurl ''
url: "http://goodcodexyz.github.io/handout"
# Build settings
repository: goodcodexyz/handout
markdown: kramdown
collections:
  - tasks
