---
title: Junior Coders
timezone: UTC
collections:
  activities:
    title: Activities
    output: true
  challenges:
    title: Challenges
    output: true
  posts:
    title: Posts
    output: true
  tasks:
    title: Tasks
    output: true
  uploads:
    title: Uploads
    output: true
description: Check out the cool things you can build using Scratch! Happy coding!
baseurl: ""
url: http://goodcodexyz.github.io/handout
repository: goodcodexyz/handout
markdown: kramdown
exclude: [archive]
